export const GET_BRIAN = 'GET_BRIAN';
export const GET_REALTORS = 'GET_REALTORS';
export const REALTOR_ERROR = 'REALTOR_ERROR';
export const GET_LANDING_IMG = 'GET_LANDING_IMG';
export const GET_BRIAN_HEADSHOT = 'GET_BRIAN_HEADSHOT';
export const GET_TESTIMONIALS = 'GET_TESTIMONIALS';
